# Generated by Django 5.1.6 on 2025-04-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_booking', '0002_guestbooking_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
